// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkv-7KA2iWu2GbXWl2qe-yLJ6JkXT254k',
    appId: '1:460969509561:web:6e8e91948cf08314d7d168',
    messagingSenderId: '460969509561',
    projectId: 'project-2-8c0d0',
    authDomain: 'project-2-8c0d0.firebaseapp.com',
    storageBucket: 'project-2-8c0d0.firebasestorage.app',
    measurementId: 'G-8DEBG42Q2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhfeZwtOInobulUsqxtUgDPAukENS1m0',
    appId: '1:460969509561:android:cae75a6d294c48d2d7d168',
    messagingSenderId: '460969509561',
    projectId: 'project-2-8c0d0',
    storageBucket: 'project-2-8c0d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbg2yhmEzqgm2Hc0LnPirbSi3HT4k-HE',
    appId: '1:460969509561:ios:f1775e819e8a3ad8d7d168',
    messagingSenderId: '460969509561',
    projectId: 'project-2-8c0d0',
    storageBucket: 'project-2-8c0d0.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIbg2yhmEzqgm2Hc0LnPirbSi3HT4k-HE',
    appId: '1:460969509561:ios:f1775e819e8a3ad8d7d168',
    messagingSenderId: '460969509561',
    projectId: 'project-2-8c0d0',
    storageBucket: 'project-2-8c0d0.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkv-7KA2iWu2GbXWl2qe-yLJ6JkXT254k',
    appId: '1:460969509561:web:89c438f55b4d4249d7d168',
    messagingSenderId: '460969509561',
    projectId: 'project-2-8c0d0',
    authDomain: 'project-2-8c0d0.firebaseapp.com',
    storageBucket: 'project-2-8c0d0.firebasestorage.app',
    measurementId: 'G-Z62Y8MMCH2',
  );
}
